
name: Scrape Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow daily at midnight (adjust as needed)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium

      - name: Download ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -N https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/

      - name: Run scraper
        run: |
          python etsy_scraper.py  # Replace with the actual name of your scraper script

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add necklaces_pendant_scraped_data.csv  # Adjust file name as needed
          git commit -m 'Update scraped data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
